language: php

notifications:
  email:
    on_success: never
    on_failure: change
  slack:
    rooms:
      - wsu-ucomm:n2TLZRJd84rMOMbkKthSEMgS
    on_success: change
    on_failure: always
    on_start: never

branches:
  only:
    - master

matrix:
  include:
    - php: 5.6
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 7.0
      env: WP_VERSION=latest WP_MULTISITE=1
    - php: 5.6
      env: WP_TRAVISCI=phpcs

before_script:
    - |
      # Remove Xdebug for a huge performance increase, but not from nightly or hhvm:
      stable='^[0-9\.]+$'
      if [[ "$TRAVIS_PHP_VERSION" =~ $stable ]]; then
        phpenv config-rm xdebug.ini
      fi
    - |
      # Export Composer's global bin dir to PATH, but not on PHP 5.2:
      if [[ ${TRAVIS_PHP_VERSION:0:3} != "5.2" ]]; then
        composer config --list --global
        export PATH=`composer config --list --global | grep '\[home\]' | { read a; echo "${a#* }/vendor/bin:$PATH"; }`
      fi
    - |
      # Install the specified version of PHPUnit depending on the PHP version:
      if [[ "$WP_TRAVISCI" == "travis:phpunit" ]]; then
        case "$TRAVIS_PHP_VERSION" in
          7.1|7.0|hhvm|nightly)
            echo "Using PHPUnit 5.7"
            composer global require "phpunit/phpunit=5.7.*"
            ;;
          5.6|5.5|5.4|5.3)
            echo "Using PHPUnit 4.8"
            composer global require "phpunit/phpunit=4.8.*"
            ;;
          5.2)
            # Do nothing, use default PHPUnit 3.6.x
            echo "Using default PHPUnit, hopefully 3.6"
            ;;
          *)
            echo "No PHPUnit version handling for PHP version $TRAVIS_PHP_VERSION"
            exit 1
            ;;
        esac
      fi
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION
      fi
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh && nvm install 6
        npm install
        composer install
      fi
    - phpunit --version
    - node --version
    - npm --version
    - composer --version

script:
    - |
      if [[ ! -z "$WP_VERSION" ]] ; then
        phpunit
      fi
    - |
      if [[ "$WP_TRAVISCI" == "phpcs" ]] ; then
        grunt
      fi
